### ISSUE TITLE
OnPlayerLeaveDynamicArea - Infinite loop

### ISSUE THREAD

**Issue by spmn** [samp-incognito/samp-streamer-plugin#60]
For more than 3 months I randomly get errors about OnPlayerLeaveDynamicArea - apparently it is caught in sort of infinite loop. Here it is output from crashdetect:

```
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 21823 past array upper bound 1999
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 0020c460 in public OnPlayerLeaveDynamicArea (playerid=17, areaid=21823) at mode.pwn:34090
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 1130233856 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=1130233856, areaid=6) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 544501365 past array upper bound 1999
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 0020c460 in public OnPlayerLeaveDynamicArea (playerid=73, areaid=544501365) at mode.pwn:34090
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1503238594
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1503238594, areaid=-601295336) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1610612481
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1610612481, areaid=-193) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -2139062204
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-2139062204, areaid=-1610612668) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 33488896 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=33488896, areaid=66176) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1526726589
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1526726589, areaid=-1610612736) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 16777215 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=16777215, areaid=-12615680) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -2147483585
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-2147483585, areaid=17) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1115684609
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1115684609, areaid=-193) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 33488896 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=33488896, areaid=356) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 1325400131 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=1325400131, areaid=-2105540608) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 16777215 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=16777215, areaid=-12615680) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 65536 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=65536, areaid=267983644) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 402784256 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=402784256, areaid=589824) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 5185547 past array upper bound 1999
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 0020c460 in public OnPlayerLeaveDynamicArea (playerid=0, areaid=5185547) at mode.pwn:34090
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 10883757 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=10883757, areaid=-536870912) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1879048192
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1879048192, areaid=1811939328) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1359941177
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 0020c460 in public OnPlayerLeaveDynamicArea (playerid=0, areaid=-1359941177) at mode.pwn:34090
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 1127458669 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=1127458669, areaid=72) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 65536 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=65536, areaid=-1106836052) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -1258225664
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1258225664, areaid=458752) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 10874594 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=10874594, areaid=-335544320) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at index 536870913 past array upper bound 401
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=536870913, areaid=671088640) at mode.pwn:33978
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:06] [debug]  Accessing element at negative index -234155271
[23/06/2015 00:30:06] [debug] AMX backtrace:
[23/06/2015 00:30:06] [debug] #0 0020c460 in public OnPlayerLeaveDynamicArea (playerid=6, areaid=-234155271) at mode.pwn:34090
[23/06/2015 00:30:06] [debug] Run time error 4: "Array index out of bounds"


// more than 800k lines ...


[23/06/2015 00:30:43] [debug] AMX backtrace:
[23/06/2015 00:30:43] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=190626224, areaid=184548632) at mode.pwn:33978
[23/06/2015 00:30:43] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:43] [debug]  Accessing element at index 644236509 past array upper bound 401
[23/06/2015 00:30:43] [debug] AMX backtrace:
[23/06/2015 00:30:43] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=644236509, areaid=-590544896) at mode.pwn:33978
[23/06/2015 00:30:43] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:43] [debug]  Accessing element at index 16928 past array upper bound 401
[23/06/2015 00:30:43] [debug] AMX backtrace:
[23/06/2015 00:30:43] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=16928, areaid=50339) at mode.pwn:33978
[23/06/2015 00:30:43] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:43] [debug]  Accessing element at index 17286 past array upper bound 401
[23/06/2015 00:30:43] [debug] AMX backtrace:
[23/06/2015 00:30:43] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=17286, areaid=-23592960) at mode.pwn:33978
[23/06/2015 00:30:43] [debug] Run time error 4: "Array index out of bounds"
[23/06/2015 00:30:43] [debug]  Accessing element at negative index -1
[23/06/2015 00:30:43] [debug] AMX backtrace:
[23/06/2015 00:30:43] [debug] #0 002097b8 in public OnPlayerLeaveDynamicArea (playerid=-1, areaid=0) at mode.pwn:33978
[23/06/2015 00:30:43] [debug] Server crashed due to an unknown error
[23/06/2015 00:30:43] [debug] Native backtrace:
[23/06/2015 00:30:43] [debug] #0 f74b4e8b in _ZN10StackTraceC1EPv () from plugins/crashdetect.so
[23/06/2015 00:30:43] [debug] #1 f74adbcf in _ZN11CrashDetect20PrintNativeBacktraceERSoPv () from plugins/crashdetect.so
[23/06/2015 00:30:43] [debug] #2 f74aedbc in _ZN11CrashDetect20PrintNativeBacktraceEPv () from plugins/crashdetect.so
[23/06/2015 00:30:43] [debug] #3 f74af226 in _ZN11CrashDetect11OnExceptionEPv () from plugins/crashdetect.so
[23/06/2015 00:30:43] [debug] #4 f74b4adc in ?? () from plugins/crashdetect.so
[23/06/2015 00:30:43] [debug] #5 f77a2410 in ?? ()
[23/06/2015 00:30:43] [debug] #6 f64ae2d5 in ?? () from plugins/streamer.so
[23/06/2015 00:30:43] [debug] #7 f64b7b4b in ?? () from plugins/streamer.so
[23/06/2015 00:30:43] [debug] #8 f6474bc5 in ProcessTick () from plugins/streamer.so
[23/06/2015 00:30:43] [debug] #9 080d1852 in ?? () from samp03svr
[23/06/2015 00:30:43] [debug] #10 080aec2c in ?? () from samp03svr
[23/06/2015 00:30:43] [debug] #11 080a9e9a in ?? () from samp03svr
[23/06/2015 00:30:43] [debug] #12 f74eebd6 in __libc_start_main () from /lib32/libc.so.6
[23/06/2015 00:30:43] [debug] #13 0804b4e1 in ?? () from samp03svr
```

As you can see, callback is called with params totally random until server crashes.
I will upload entire log if you need it. (81 MB big)

Plugins loaded: crashdetect (latest version), mysql_static (R39-2, also tried R39-3 compiled locally), sscanf (2.8.1), Whirlpool, streamer (2.7.6), timerfix (1.5), CTime, MapAndreas (1.2.1).

[Linux]

**Comment by ikkentim** [comment]
You should update to 2.7.7. This should fix the issue.

**Comment by samp-incognito** [comment]
"Array index out of bounds" means your script is accessing an invalid index in an array. I would check your script for logic errors.

**Comment by spmn** [comment]
Yes, I get "Array index out of bounds" because of parameters values which are invalid, eg: (playerid=-1879048192, areaid=1811939328); (playerid=1325400131, areaid=-2105540608)

**Comment by ikkentim** [comment]
Could you try updating to the latest version and see if the bug still exists(2.7.7). New versions tend to fix bugs.

**Comment by spmn** [comment]
@ikkentim: according to commits, this update has nothing to do with this problem. However, I've updated to 2.7.7 and crashes still occur.

**Comment by samp-incognito** [comment]
I doubt think this has anything to do with the plugin. I think your script has an array going out of bounds somewhere, which is corrupting the stack and causing all of these runtime errors.

It looks like it starts when OnPlayerLeaveDynamicArea is called with a playerid of -1 and an areaid of 0? That should never happen. Are you sure you aren't manually executing the callback somewhere in your script? (Of course, the stack might have already been corrupted at this point for whatever reason.)

**Comment by Southclaw** [comment]
It could be a bad hook, I've had this exact problem before and it's just CallLocalFunction accessing the wrong data on the stack due to a mismatch of format specifiers and parameters passed.

**Comment by spmn** [comment]
@samp-incognito I double-checked all libraries I'm using and there isn't any direct call to OnPlayerLeaveDynamicArea. However, could calling Streamer_(Get/Set)ArrayData with invalid parameters (like invalid object id) corrupt stack?
@Southclaw I'll check all parameters of functions. Actually, this may be the problem because I've experienced random crashes like this on 0.3z R4 when OnUnoccupiedVehicleDamage header modified, adding velocity parameters, but compiler didn't warn me about them at compile-time, despite I updated a_samp file.

**Comment by spmn** [comment]
Update:

I've logged all OnPlayerLeaveDynamicArea calls and I found a pattern: right before parameters goes crazy, there is always atleast one call of OnPlayerLeaveDynamicArea with areaid = 73. Areas ID 1-72 are static, so they are created at script init and they aren't destroyed during runtime. All areas whose ID is greater than or equal to 73 are dynamically created and destroyed. Those areas could be destroyed using a command (no such command was typed so this hadn't triggered callback), by player disconnect (no player disconnected, so this hadn't triggered callback) or by OnPlayerLeaveDynamicArea itself (this could have happened). So, when a player exits an area, it is automatically destroyed. IIRC, I started to experience this bug after I switched to v2.7.4. I assume that that fb291f05a0e850442c61611522157eb7847daf97 (and maybe 038ee90fef84ff275eb5a5c2417033fe7ee5d947) has (have) something to do with my problem.

Since my mode uses some things added in v2.7.4+, could you provide me linux binaries of the latest streamer version without those commits, so I won't have to downgrade?
